//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___USERNAME___ on ___DATE___.
//___COPYRIGHT___
//

#ifndef ___PROJECTNAMEASIDENTIFIER_______FILEBASENAMEASIDENTIFIER_______FILEEXTENSION___
#define ___PROJECTNAMEASIDENTIFIER_______FILEBASENAMEASIDENTIFIER_______FILEEXTENSION___


#endif
